// JSON = JAVASCRIPT OBJECT NOTATION;
// UTILIZADO PARA COMUNICAÇÃO ENTRE SERVIÇOS, EX: BACK END <-> FRONT END;
// BASICAMENTE UM TIPO DE DADO PADRONIZADO, QUE LEMBRA MUITO OS OBJETOS DO JAVASCRIPT.
// RIGOROSO NA ESTRUTURA, OU SEJA, VOCÊ DEVE SEGUIR O PADRÃO IMPOSTO POR ESTE FORMATO;
// APENAS ASPAS DUPLAS;
// NÃO ACEITA COMENTÁRIOS.


let pessoa = {
    "nome": "Derick",
    "idade": 26
}

console.log(pessoa.nome);
console.log(pessoa.idade);